### PR TITLE
Multi-track and multi-page OSC message support

### PR DESCRIPTION
**Pull request by bjorn-felle**
Adds support for a new OSC message which allows you to control a specific parameter on a specific page on a specific track in Bitwig. The OSC message contains the full path to the parameter, and Bitwig will return the message to controls which are receiving it to update the control if the value is changed in Bitwig. Bitwig will automatically switch to the correct track/page if it isn't currently on screen when the value is changed.

The OSC message should be structured as follows:

`/track/n/params/y/z/value x`

Replace `n` with the track number, `y` with the parameter page number (1-8), and `z` with the parameter number (1-8). Send x as an argument representing the value of the control.

### CODE REVIEW

**Comment by git-moss** [comment]
Sorry, I don't want to add that to the main branch.

**Comment by KGZM** [comment]
@git-moss Is there a technical limitation on multi track controls? 

Currently the OSC implementation seems very cursor driven, in other words it lets you access the controls you can see in one view of Bitwig without looking at Bitwig. 

Using midi learn with an arbitrary MIDI controller you can simultaneously access controls that you cannot see in a single view.

For live usage, rather than cursor-based studio usage, being able to manipulate the parameters of different tracks simultaneously seems essential.

The power of OSC would seem to lie in being able to create performance controls with a 1:1 correlation to parameters without having to page and manage cursor focus.

Do you have any recommendations for pursuing that kind of workflow with this extension?

**Comment by bjorn-felle** [comment]
@KGZM if I've read the sources correctly, the cursor-based nature is related to way these properties and funtions are exposed by Bitwig's API. Unfortunately there's no other way to address an arbitrary control other than by asking the API to move the cursor to that control in order to obtain a reference to it. I contacted Bitwig and asked if it may be possible to have the public API extended to allow more direct access to devices from extensions, and the answer was basically "no". My fork of moss does work in that it allows you to address devices using OSC by effectively asking the API, through OSC, to move the cursor before sending the value. This became a problem when sending values to multiple controls simultaneously so it wasn't usable in a live context. I do feel this limits Bitwig's live application somewhat. I recall reading that there have been developments in live performance functions in Bitwig 5 but I'm not familiar with what they are or whether they allow this kind of control. In the end I decided to use a touch screen and ultimately built a controller app which alows me to do it all over MIDI. You could do the same with other MIDI controllers of course though MIDI doesn't give nearly as much control as is possible with OSC in some applications, so wouldn't always be an option. I hope Bitwig do ultimately make it possible for extensions to access devices more directly, or perhaps implement OSC natively. For now, with Bitwig, it seems that MIDI is the best option if you want this level of control. There are also software options which can interpret OSC messages and translate them to MIDI commands, which works well with Bitwig but doesn't give the feedback that is possible with OSC.

**Comment by KGZM** [comment]
Ah, sounds like no clever controller scripting will help us then. 

For my use case (two performers with independent instruments + some shared globals) I _might_ be able to get away with multiple instances of the OSC controller script pinned to different tracks with some supplemental MIDI mappings.

**Comment by git-moss** [comment]
Bitwig 5 introduced now the concept of Project Remote Controls which allow to map any parameter in the project.
I did several videos about the topic, e.g. this one:
https://www.youtube.com/watch?v=0hMr1NkltVM

**Comment by bjorn-felle** [comment]
Thank you Jürgen, this is a very informative reply and I enjoyed the video you made about this. Seems like a good time to renew my update subscription! Do you know, or is it documented, which OSC messages control the project remote controls? I'm really happy to see that this has been added. I've at times become frustrated that I can't send a macro to multiple devices like I would have in Bitwig using Spider CV splitter for example. This is a really elegant solution and looks like it will allow a much smoother experience using Bitwig live.

**Comment by git-moss** [comment]
All OSC messages are documented in the OSC chapter in the DrivenByMoss manual.

**Pull request closed without merging**
