### PR TITLE
Experiment: kontrolf1 4 channel clip launcher with 2 remote controls

### PR DESCRIPTION
**Pull request by haszari**
Work in progress.

Ultimate goal:

- 4x4 clip launcher grid
  - navigate grid focus rect up/down in pages with buttons or encoder
  - launch clips
  - see clips as colours
  - see clip play state with brightness or flashing
- config param for launcher grid channels (so can't accidentally nudge)
- knobs & faders are channel remotes

### CODE REVIEW

**Comment by haszari** [comment]
Closing, wrong repo

**Comment by git-moss** [comment]
I am sorry but I cannot accept pull requests for devices I do not own and therefore cannot support.

**Comment by haszari** [comment]
No problem, I'm experimenting and will work with my forked build. 

Thanks for all your work on this framework!

**Comment by haszari** [comment]
@git-moss – if you have a moment to give me some feedback / help I'd really appreciate it! No worries if not, I am making progress. 

Here's my branch: https://github.com/git-moss/DrivenByMoss/compare/master...haszari:DrivenByMoss:try/kontrolf1-4-channel-clip-launcher-with-2-remote-controls

- I have a session grid / clip launcher (SessionView + PadGrid) set up. 
- It's working correctly from the simulated / virtual GUI - triggering and stopping clips.
- **Question: how do I connect the SessionView / PadGrid to MIDI input?**
- My pads are set up to send MIDI notes starting at note 36. 

Again, thanks again for all your work on Bitwig. 🙌

**Comment by git-moss** [comment]
I don't have time to support people in development but some hints which should get you going:
Look at the
- *Definition classes for the MIDI port lookups.
- *Setup classes in the register* Methods for the specific MIDI CC/note assignments
- For pads there are some specific *Grid classes if you need to transform to/from 36...

**Comment by haszari** [comment]
Thanks for the tips! I found a few possible issues with my code (mostly not calling `super.createObservers()`), however my clip launcher is still not responding to MIDI input.

**Comment by haszari** [comment]
Thanks again for the help! I switched back to implementing in Bitwig API direct, and I've got a working mapping for now. Happy days!

https://github.com/haszari/wide-bitwig-controller-extensions/tree/main/TraktorKontrolF1

**Pull request closed without merging**
